name: build

on:
  push:
    paths-ignore:
      - '*.md'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'images/**'

jobs:
  build-maven:
    name: Builds and tests for Maven under Batect
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Restore Batect caches
        uses: actions/cache@master
        env:
          cache-name: batect-cache
        with:
          path: ~/.batect
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/batect.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Manage Batect telemetry
        run: ./batect --permanently-enable-telemetry

      - name: Restore Maven caches
        uses: actions/cache@master
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test with Maven under Batect
        run: ./batect build

      - name: Generate Coverage badge
        if: ${{ github.ref == 'refs/head/master' }}
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-badge: target/site/jacoco/jacoco.csv
          badges-directory: target/site/jacoco/badges

      - name: Publish Coverage badge
        if: ${{ github.ref == 'refs/head/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site/jacoco

      - name: Execute run script
        run: ./batect -o quiet demo

      - name: Execute run script for Java
        run: ./batect -o quiet java-demo
