name: Full build and verify

on: [push]

jobs:
  build:
    name: Builds, verifies, and publishes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@master
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          version: 11

      - name: Build and verify
        run: >
          ./mvnw -C
          -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
          verify

#      - name: Deploy to Github package registry
#        env:
#          GITHUB_USERNAME: x-access-token
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: >
#          ./mvnw -C
#          --settings github-settings.xml
#          -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
#          -DskipTests -DskipITs
#          -Djacoco.skip=true -Dktlint.skip=true -Dowasp.skip=true
#          deploy
